### ISSUE TITLE
getResources call is weird

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-connector-api-node#15]
mbedConnectorApi.getEndpoints([callback], [options])

Should be

mbedConnectorApi.getEndpoints([options], [callback])

Or even

mbedConnectorApi.getEndpoints([type], [callback])

Now it does not feel like node.js. Callback is always last.

@bridadan

**Comment by bridadan** [comment]
Ah yes, I believe the [options] were added later and to avoid a major version bump, but you're right that 
`mbedConnectorApi.getEndpoints([options], [callback])` is more in line with node.js style. This affects pretty much every function in the API. This would have to be major version bump.

**Comment by janjongboom** [comment]
@bridadan Could be compatible with both, just checking if arg[0] === function and arg[1] is string or object and swap it around.

**Comment by bridadan** [comment]
True, though that feels a bit strange. Have seen many libraries that do something like that? Being able to arbitrarily switch argument order seems kinda funny

**Comment by RomanSaveljev** [comment]
Yes, callback should be the last argument to help with reading the code.

**Comment by bridadan** [comment]
@RomanSaveljev, @janjongboom, thanks a lot for the feedback. Not sure I have time to dedicate to this right now, but I think is probably a sane change for the next major release. Let's keep this issue open to track it.

**Comment by bridadan** [comment]
Fixed by #21
