### ISSUE TITLE
Travis is failing on npm install

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-connector-api-node#17]
Travis is failing right now on the `npm install` step. Looks like an issue with the `pty.js` node module. See this Travis build: https://travis-ci.org/ARMmbed/mbed-connector-api-node/builds/141054371

**Comment by BlackstoneEngineering** [comment]
Have you checked the version of npm? I had to do a bunch of schenanigans for the circle CI builds for the python library to get things updated b/c the default VM's are suuuuuper old and stable.

**Comment by bridadan** [comment]
This isn't an issue any more, closing
